name: contracts-ci
on:
  push:
    paths:
      - "contracts/**"
      - ".github/workflows/ci-contracts.yml"
  pull_request:
    paths:
      - "contracts/**"
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Install deps (forge-std)
        working-directory: contracts
        run: forge install foundry-rs/forge-std --no-commit -q
      - name: Build & test
        working-directory: contracts
        run: |
          forge fmt --check
          forge build --sizes
          forge test -vvv
